In [1]:
import numpy as np

In [17]:
def print_obj(obj, name):
    #print("%s:\n%s\n" %(name, obj))
    print(f"{name}:\n{obj}\n")

def check_each(a, b):
    #return (a == b).astype('bool')
    return (a == b)

def check_mean(a, b):
    return np.mean (a == b)
    #return np.mean (a == b).astype('bool')

## Scalars, Vectors, Matrices

In [38]:
a = np.array(1.)
b = np.array([1., 2., 3.])
# b = np.array([[1., 2., 3.]])
c = np.array([[1., 2., 3.], [4., 5., 6.]])

print_obj(a, "a")
print_obj(b, "b")
print_obj(c, "c")

a:
1.0

b:
[1. 2. 3.]

c:
[[1. 2. 3.]
 [4. 5. 6.]]



In [39]:
print_obj(a.ndim, "a_ndim") # ndim: number of dimension  
print_obj(b.ndim, "b_dim")
print_obj(c.ndim, "c_dim")

a_ndim:
0

b_dim:
1

c_dim:
2



In [40]:
print_obj(a.shape, "a.shape")
print_obj(b.shape, "b.shape")
print_obj(c.shape, "c.shape")

a.shape:
()

b.shape:
(3,)

c.shape:
(2, 3)



## Tensors (N-dimensional array)

In [37]:
d = np.array([[[1., 2., 3. ], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12]]])
e = np.array([[[[1., 2., 3. ], [1., 2., 3. ]],[[4., 5., 6], [4., 5., 6]]],[[[7., 8., 9], [7., 8., 9]],[[10., 11., 12], [10., 11., 12]]]])
print_obj(d,"d" )
print_obj(d.ndim, "d.ndim")
print_obj(d.shape, "d.shape")

print_obj(e,"e" )
print_obj(e.ndim, "e.ndim")
print_obj(e.shape, "e.shape")

d:
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]

d.ndim:
3

d.shape:
(2, 2, 3)

e:
[[[[ 1.  2.  3.]
   [ 1.  2.  3.]]

  [[ 4.  5.  6.]
   [ 4.  5.  6.]]]


 [[[ 7.  8.  9.]
   [ 7.  8.  9.]]

  [[10. 11. 12.]
   [10. 11. 12.]]]]

e.ndim:
4

e.shape:
(2, 2, 2, 3)



In [33]:
# Quiz: what is the shape of  [[[1], [2], [3]], [[4], [5], [6]]]? 
# Answer: (2, 3, 1)

a = np.array([[[1], [2], [3]], [[4], [5], [6]]])
print_obj(a, "a")
print_obj(a.ndim, "a.ndim")
print_obj(a.shape, "a.shape")

a:
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]

a.ndim:
3

a.shape:
(2, 3, 1)



## Defining Numpy arrays

In [42]:
a = np.ones(10)
print_obj(a, "a")

a:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]



In [44]:
a = np.zeros((2, 5))
print_obj(a, "a")

a:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]



In [45]:
a = np.full((2, 5), 5)
print_obj(a, "a")

a:
[[5 5 5 5 5]
 [5 5 5 5 5]]



In [46]:
a = np.random.random((2, 3, 4))
print_obj(a, "a")

a:
[[[0.80995338 0.58563059 0.74900748 0.16894063]
  [0.02352224 0.22253463 0.67772744 0.45589746]
  [0.19473841 0.10526177 0.13153162 0.54820268]]

 [[0.51278929 0.6549396  0.94825922 0.62080948]
  [0.23707667 0.81532076 0.80461748 0.15253702]
  [0.91374492 0.03590623 0.26060953 0.0312668 ]]]



In [47]:
a = np.arange(10)
print_obj(a, "a")

a:
[0 1 2 3 4 5 6 7 8 9]



In [49]:
a = np.arange(10).astype("float")
print_obj(a, "a")

a:
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]



In [50]:
a = np.arange(10).reshape((5, 2))
print_obj(a, "a")
print_obj(a.ndim, "a.dim")
print_obj(a.shape, "a.shape")

a:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

a.dim:
2

a.shape:
(5, 2)



In [52]:
# Quiz: Create a (4, 3, 2) tensor filled with 0.0 to 23.0 
a = np.arange(24).astype("float").reshape((4, 3, 2))
print_obj(a, "a")

a:
[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]]

 [[ 6.  7.]
  [ 8.  9.]
  [10. 11.]]

 [[12. 13.]
  [14. 15.]
  [16. 17.]]

 [[18. 19.]
  [20. 21.]
  [22. 23.]]]



## Indexing & Slicing 

In [53]:
# Indexing and sclicing a vector
a = np.arange(10)

print_obj(a, "a")
print_obj(a[0], "a[0]") # 0 
print_obj(a[1], "a[1]") # 1
print_obj(a[-1], "a[-1]") #9
print_obj(a[-3], "a[-3]") #7 

a:
[0 1 2 3 4 5 6 7 8 9]

a[0]:
0

a[1]:
1

a[-1]:
9

a[-3]:
7



In [57]:
print_obj(a[0:10], "a[0:10]")
print_obj(a[0:], "a[0:]")
print_obj(a[:10], "a[:10]")
print_obj(a[:], "a[:]")

a[0:10]:
[0 1 2 3 4 5 6 7 8 9]

a[0:]:
[0 1 2 3 4 5 6 7 8 9]

a[:10]:
[0 1 2 3 4 5 6 7 8 9]

a[:]:
[0 1 2 3 4 5 6 7 8 9]



In [60]:
print_obj(a[7:], "a[7:]")
print_obj(a[:5], "a[:5]")
print_obj(a[2:5], "a[2:5]")

a[7:]:
[7 8 9]

a[:5]:
[0 1 2 3 4]

a[2:5]:
[2 3 4]



In [62]:
# Quiz: what is a[-4:]
# Quiz: waht is a[:-8]

print_obj(a[-4:], "a[-4:]")
print_obj(a[:-8], "a[:-8]")

a[-4:]:
[6 7 8 9]

a[:-8]:
[0 1]



In [65]:
print_obj(a[0:10:2], "a[0:10:2]")
print_obj(a[0:10:3], "a[0:10:3]")
print_obj(a[2:6:3], "a[2:6:3]")

a[0:10:2]:
[0 2 4 6 8]

a[0:10:3]:
[0 3 6 9]

a[2:6:3]:
[2 5]



In [68]:
print_obj(a[::-1], "a[::-1]")
print_obj(a[8:5:-1], "a[8:5:-1]")
print_obj(a[8:5], "a[8:5]")

a[::-1]:
[9 8 7 6 5 4 3 2 1 0]

a[8:5:-1]:
[8 7 6]

a[8:5]:
[]



In [71]:
# Quiz: create [9, 6, 3] using a
print_obj(a[9:0:-3], "a[9:0:-3]")

a[9:0:-3]:
[9 6 3]



In [76]:
a = np.arange(9).reshape((3, 3))
print_obj(a, "a")
print_obj(a[0][0], "a[0][0]") #0
print_obj(a[0, 0], "a[0,0]") #0
print_obj(a[1, 1], "a[1,1]") #4

a:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

a[0][0]:
0

a[0,0]:
0

a[1,1]:
4



In [82]:
# Quiz: how to access the last row? 
print_obj(a[-1, :], "a[-1,:]") #

#Quiz: how to access the second column? 
print_obj(a[:, 1], "a[:,1]") 

# Quiz: how to create [8, 5] using a ?
print_obj(a[-1:0:-1, 2], "a[-1:0:-1, 2]") 

a[-1,:]:
[6 7 8]

a[:,1]:
[1 4 7]

a[-1:0:-1, 2]:
[8 5]



In [84]:
a = np.arange(4*3*2).reshape((4,3,2))
print_obj(a, "a")
print_obj(a[2, 1, 0], "a[2, 1, 0]")

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

a[2, 1, 0]:
14



In [90]:
# Quiz: what would be a[0]
print_obj(a[0], "a[0]")

#Quiz: what would be a[0, 1]?
print_obj(a[0, 1], "a[0, 1]")

#Quiz: create [[0, 2, 4],[6, 8, 10]]
print_obj(a[0:2,:, 0 ], "")

a[0]:
[[0 1]
 [2 3]
 [4 5]]

a[0, 1]:
[2 3]

:
[[ 0  2  4]
 [ 6  8 10]]



In [95]:
# conditional indexing
a = np.arange(3*2).reshape((3,2))
print_obj(a, "a")


#Quiz: how would you create [3, 4, 5] using a?

idx = a > 2
print_obj(idx, "idx")
print_obj(a[idx], "a[idx]")

a:
[[0 1]
 [2 3]
 [4 5]]

idx:
[[False False]
 [False  True]
 [ True  True]]

a[idx]:
[3 4 5]



In [96]:
# Taking specific elements from a vector
a = np.arange(10)
idx = [0, 2, 3]
print_obj(a[idx], "a[idx]")

a[idx]:
[0 2 3]



In [103]:
a = np.arange(24).reshape((6,4))
print_obj(a, "a")

print_obj(a[:, [0,2,3]], "a[:, [0,2,3]]")
print_obj(a[ [0,2,3], :], "a[ [0,2,3], :]")
idx = ((0,0,1,5),(1,2,0,3))
print_obj(a[idx], "tuple indexing") 
idx = np.array([[0,0,1,5],[1,2,0,3]])
print_obj(a[idx], "ndarray indexing") # pay attention 

a:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

a[:, [0,2,3]]:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]

a[ [0,2,3], :]:
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]

tuple indexing:
[ 1  2  4 23]

ndarray indexing:
[[[ 0  1  2  3]
  [ 0  1  2  3]
  [ 4  5  6  7]
  [20 21 22 23]]

 [[ 4  5  6  7]
  [ 8  9 10 11]
  [ 0  1  2  3]
  [12 13 14 15]]]



## Math Operations

In [106]:
# Basic operations

a = np.arange(6).reshape((3,2))
b = np.ones((3,2))
print_obj(a, "a")
print_obj(b, "b")

# +, -, *, /
print_obj(a+b, "a+b")
print_obj(a-b, "a-b")
print_obj(a*b, "a*b")
print_obj(a/b, "a/b")

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

a+b:
[[1. 2.]
 [3. 4.]
 [5. 6.]]

a-b:
[[-1.  0.]
 [ 1.  2.]
 [ 3.  4.]]

a*b:
[[0. 1.]
 [2. 3.]
 [4. 5.]]

a/b:
[[0. 1.]
 [2. 3.]
 [4. 5.]]



In [116]:
# Unary operations
a = np.arange(6).reshape((3,2))
print_obj(a, "a")

print_obj(a.sum(), "a.sum()")
print_obj(a.sum(axis=0), "a.sum(axis=0)")
print_obj(a.sum(axis=1), "a.sum(axis=1)")

print_obj(a.mean(), "a.mean()")
print_obj(a.max(), "a.max()")
print_obj(a.min(), "a.min()")

#Quiz: Given a = np.arange(24).reshape((2, 3, 4)), what is the mean of the sum w.r.t. the last dimension 

a = np.arange(24).reshape((2, 3, 4))
print_obj(a, "a")
print_obj(a.sum(axis=2), "a.sum(axis=2)")
print_obj(a.sum(axis=2).mean(), "a.sum(axis=2).mean()")

a:
[[0 1]
 [2 3]
 [4 5]]

a.sum():
15

a.sum(axis=0):
[6 9]

a.sum(axis=1):
[1 5 9]

a.mean():
2.5

a.max():
5

a.min():
0

a:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

a.sum(axis=2):
[[ 6 22 38]
 [54 70 86]]

a.sum(axis=2).mean():
46.0



In [118]:
# vector do product
a = np.arange(3).astype("float")
b = np.ones(3)
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a, b), "a dot b")

a:
[0. 1. 2.]

b:
[1. 1. 1.]

a dot b:
3.0



In [122]:
# matrix dot product, matrix multiplication
a = np.arange(6).reshape((3,2))
b = np.ones((2, 3))
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a, b), "a dot b")
print_obj(a@b, "a@b")

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[[1. 1. 1.]
 [1. 1. 1.]]

a dot b:
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]

a@b:
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]



In [136]:
# tensor dot product, tensor multiplication

a = np.arange(24).reshape((4, 3, 2))
b = np.ones((4, 2, 3))
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a, b), "a dot b")
print_obj(a@b, "a@b")

# Quiz: what would happen if a.shape=(4,3, 2) and b.shape=(2, 3)
print_obj(np.dot(a, b), "a dot b") # 4, 3, 3
print_obj(np.matmul(a,b), "np.matmul(a,b)")

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

b:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]

a dot b:
[[[[ 1.  1.  1.]
   [ 1.  1.  1.]
   [ 1.  1.  1.]
   [ 1.  1.  1.]]

  [[ 5.  5.  5.]
   [ 5.  5.  5.]
   [ 5.  5.  5.]
   [ 5.  5.  5.]]

  [[ 9.  9.  9.]
   [ 9.  9.  9.]
   [ 9.  9.  9.]
   [ 9.  9.  9.]]]


 [[[13. 13. 13.]
   [13. 13. 13.]
   [13. 13. 13.]
   [13. 13. 13.]]

  [[17. 17. 17.]
   [17. 17. 17.]
   [17. 17. 17.]
   [17. 17. 17.]]

  [[21. 21. 21.]
   [21. 21. 21.]
   [21. 21. 21.]
   [21. 21. 21.]]]


 [[[25. 25. 25.]
   [25. 25. 25.]
   [25. 25. 25.]
   [25. 25. 25.]]

  [[29. 29. 29.]
   [29. 29. 29.]
   [29. 29. 29.]
   [29. 29. 29.]]

  [[33. 33. 33.]
   [33. 33. 33.]
   [33. 33. 33.]
   [33. 33. 33.]]]


 [[[37. 37. 37.]
   [37. 37. 37.]
   [37. 37. 37.]
   [37. 37. 37.]]

  [[41. 41. 41.]
   [41. 41. 41.]
   

## Shape Manipulation

In [138]:
# Reshape

a = np.arange(24).reshape((2, 3, 4))
print_obj(a, "a")

b = a.reshape((6, 4))
print_obj(b, "b")

#Quiz: what would d=a.reshape((6, 4, -1)) look like? 
d=a.reshape((6, 4, -1))
print_obj(d, "d")

a:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

b:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

d:
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]



In [143]:
# adding an extra dimension
a = np.arange(3)
print_obj(a, "a")

print_obj(a[:, None], "a[:, None]")

# Quiz: how to make a = np.ones((3, 4)) into shape(3, 1, 1, 4) using reshape and None?
a = np.ones((3, 4))
print_obj(a, "a")
a = a[:, None]
print_obj(a[:, None], "a[:, None]")
a = a.reshape((3, 1, -1, 4))
print_obj(a.reshape((3, 1, -1, 4)), "a.reshape((3, 1, -1, 4))")

a:
[0 1 2]

a[:, None]:
[[0]
 [1]
 [2]]

a:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

a[:, None]:
[[[[1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]]]]

a.reshape((3, 1, -1, 4)):
[[[[1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]]]]



In [152]:
# stack, concatenation
a = np.ones((3, 2))
b = np.zeros((3, 2))
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.vstack([a, b]), "a, b  vstack")
print_obj(np.hstack([a, b]), "a, b hstack")

print_obj(np.concatenate([a, b], axis = 0), "a, b concat, axis = 0")
print_obj(np.concatenate([a, b], axis = 1), "a, b concat, axis = 1")

# Quiz: would concatenating two tensors whose space are (4, 3, 2) and (5, 4, 2) on axis = 2 work?  Nope 
# a = np.ones((4,3, 2))
# b = np.zeros((5,4, 2))
# print_obj(np.concatenate([a, b], axis = 2), "a, b concat, axis = 2")

a:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

b:
[[0. 0.]
 [0. 0.]
 [0. 0.]]

a, b  vstack:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

a, b hstack:
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]

a, b concat, axis = 0:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

a, b concat, axis = 1:
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]



In [155]:
# matrix transpose
a = np.arange(6).reshape((3, 2))
print_obj(a, "a")

print_obj(a.T, "a.T")

a:
[[0 1]
 [2 3]
 [4 5]]

a.T:
[[0 2 4]
 [1 3 5]]



In [158]:
# Tensor transpose
a = np.arange(24).reshape((4, 3, 2))
print_obj(a, "a")

b = np.transpose(a, [0, 2, 1])
print_obj(b, "swap axis 1 and 2")
print_obj(b.shape, "b.shape")

c = np.transpose(a, [1, 0, 2])
print_obj(c, "swap axis 0 and 1")
print_obj(c.shape, "c.shape")

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

swap axis 1 and 2:
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]

b.shape:
(4, 2, 3)

swap axis 0 and 1:
[[[ 0  1]
  [ 6  7]
  [12 13]
  [18 19]]

 [[ 2  3]
  [ 8  9]
  [14 15]
  [20 21]]

 [[ 4  5]
  [10 11]
  [16 17]
  [22 23]]]

c.shape:
(3, 4, 2)



## Broadcasting 

In [160]:
# vector and scalar
a = np.arange(3)
b = 2. 
print_obj(a, "a")

print_obj(a+b, "a+b")
print_obj(a-b, "a-b")
print_obj(a*b, "a*b")
print_obj(a/b, "a/b")

a:
[0 1 2]

a+b:
[2. 3. 4.]

a-b:
[-2. -1.  0.]

a*b:
[0. 2. 4.]

a/b:
[0.  0.5 1. ]



In [171]:
# matrix and vector
a = np.arange(6).reshape((3, 2))
b = np.arange(2) + 1
print_obj(a, "a")
print_obj(b, "b")

print_obj(a + b, "a + b")

#Quiz: what would happen if b were np.arange(2).reshape((2, 1))? How about np.arange(2).reshape((1,2))? 
# b = np.arange(2).reshape((2, 1)) 
# print_obj(a + b, "a + b") # nope

b = np.arange(2).reshape((1, 2)) 
print_obj(b, "b")
print_obj(a + b, "a + b")

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[1 2]

a + b:
[[1 3]
 [3 5]
 [5 7]]

b:
[[0 1]]

a + b:
[[0 2]
 [2 4]
 [4 6]]



In [173]:
# tensor and matrix
a = np.arange(12).reshape((2, 3, 2))
b = np.arange(6).reshape((3, 2))
print_obj(a, "a")
print_obj(b, "b")

print_obj(a + b, "a + b")

#Quiz: how can we use None to do  a + b?
b = b[None, :, :]

print_obj(a + b, "a + b")

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

b:
[[0 1]
 [2 3]
 [4 5]]

a + b:
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[ 6  8]
  [10 12]
  [14 16]]]

a + b:
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[ 6  8]
  [10 12]
  [14 16]]]



In [ ]:
def sigmoid(x):
    return 1./(1. + np.exp(-x))

# Define a function that, given M of shape (m,n) and W of shape (4n, n), executes the following:
# - Take the first half rows of M
# - Take the second half rows of M
# - Take the odd-numbered rows of M
# - Take the even-numbered rows of M
# - Append them horizontally in the listed order so that you obtain a matrix X of shape (m/2, 4n)
# - Linearly transform X with W so that you obtain a matrix Y of shape (m/2, n)
# - Put Y through the sigmoid function
# - Obtain the sum of the row-wise mean

def foo(M, W):
    m = M.shape[0]
    firstHalf = M[:m/2,:]
    secHalf = M[m/2:, :]
    oddHalf = M[1::2, :]
    evenHalf = M[0::2, :]
    X = np.concatenate([firstHalf, secHalf, oddHalf, evenHalf], axis = 1)
    Y = np.matmul(X, W)
    y = sigmid(Y)
    result = np.sum(y.mean(axis=0))
    return result 

